DEBUG_MODE: false

CRONTAB:
    USER: ws

WATER_SENSOR:
    IN_GPIO_W: 26
    OUT_GPIO_W: 20
    WATERLVL_VALUE: true  # will only be used if debug mode is on.

PUMP_CONTROL:
    MAX_TIME_ON: 180
    RELAIS_1_GPIO: 21
