DEBUG_MODE: true

CRONTAB:
    USER: cedric

WATER_SENSOR:
    IN_GPIO_W: [5, 6, 13, 19, 26]
    OUT_GPIO_W: 20
    WATERLVL_VALUE: 25  # will only be used if debug mode is on.

PUMP_CONTROL:
    MAX_TIME_ON: 10
    RELAIS_1_GPIO: 21
